### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by alex3236** [yaolifeng0629/del-repos#12]
1. Repository type listed should be `owner`. I don't think anyone want to delete a repo using this tool as a **member**. Of course, it can be passed as an arg, but it shouldn't be `all` by default. Especially since there is no distinction in the menu between participating and owned repos.
https://github.com/yaolifeng0629/del-repos/blob/d9932dd890e508063bc3c9d1c01a4ba82e16a2ee/src/services/gitee.ts#L18
https://github.com/yaolifeng0629/del-repos/blob/d9932dd890e508063bc3c9d1c01a4ba82e16a2ee/src/services/github.ts#L18
![](https://github.com/user-attachments/assets/19cd64c5-35f4-4be0-9a03-ae121060351f)
2. Do a double check after repos selected. It's difficult for people to concentrate on a scrolling menu to determine if there are no items selected by mistake.
3. No need to pop up the create token page every time. Change the logic, e.g. when the user presses enter without filling in the token.
4. Allow custom sorting, such as oldest, or alphabetically.

**Comment by alex3236** [comment]
Of course, thank you still for creating this wonderful tool. If you have a plan but lack the time, I'd love to submit a PR

**Comment by yaolifeng0629** [comment]
@alex3236 Thank you for your feedback

1. The starting point is to display all of its repositories to authorized users, including those that participate as members and those that are private. This way, users can flexibly delete any warehouses related to them.

2. To prevent misoperation, an optimization item for a secondary confirmation step can be added after the user confirms the deletion. This will greatly reduce the risk of accidental deletion.

3. Considering that some users may not be familiar with the process of obtaining or saving tokens, we choose to display the page for creating tokens every time. This is a temporary solution, welcome to explore more elegant solutions.

4. Currently, the warehouse list is sorted by project activity. This helps users quickly find the most commonly used or important warehouses.

**Comment by alex3236** [comment]
> 1. The starting point is to display all of its repositories to authorized users, including those that participate as members and those that are private. This way, users can flexibly delete any warehouses related to them.

For this point, why not show the repo owner? In https://github.com/ruanyf/weekly/issues/4644 the repo is shown as `owner/name` but now it seems to be `name`, which makes it impossible to distinguish the owner of a repo with the same name

**Comment by yaolifeng0629** [comment]
> > 1. The starting point is to display all of its repositories to authorized users, including those that participate as members and those that are private. This way, users can flexibly delete any warehouses related to them.
> 
> For this point, why not show the repo owner? In [ruanyf/weekly#4644](https://github.com/ruanyf/weekly/issues/4644) the repo is shown as `owner/name` but now it seems to be `name`, which makes it impossible to distinguish the owner of a repo with the same name

@alex3236 Sorry, I didn't understand the sentence 'but now it sees to be name, which makes it impossible to distinguish the owner of a repo with the same name'. Could you please give me an example

**Comment by yaolifeng0629** [comment]
> > 1. The starting point is to display all of its repositories to authorized users, including those that participate as members and those that are private. This way, users can flexibly delete any warehouses related to them.
> 
> For this point, why not show the repo owner? In [ruanyf/weekly#4644](https://github.com/ruanyf/weekly/issues/4644) the repo is shown as `owner/name` but now it seems to be `name`, which makes it impossible to distinguish the owner of a repo with the same name

@alex3236 You are right. This is a current issue that exists

**Comment by yaolifeng0629** [comment]
> > 1. The starting point is to display all of its repositories to authorized users, including those that participate as members and those that are private. This way, users can flexibly delete any warehouses related to them.
> 
> For this point, why not show the repo owner? In [ruanyf/weekly#4644](https://github.com/ruanyf/weekly/issues/4644) the repo is shown as `owner/name` but now it seems to be `name`, which makes it impossible to distinguish the owner of a repo with the same name


@alex3236 The latest version has been released and fixed, see [#1.0.13](https://github.com/yaolifeng0629/del-repos/releases/tag/1.0.13)
