### ISSUE TITLE
Failed to delete gitee repository

### ISSUE THREAD

**Issue by FergusHuang** [yaolifeng0629/del-repos#14]
rock@rock2310:~$ del-repos -v
1.0.13
rock@rock2310:~$ del-repos
Welcome to the Repository Deletion CLI Tool
? Choose a platform: Gitee
Gitee support is now available.
Opening Gitee token generation page...
? Please enter your Gitee token: .....
✔ Fetched repositories successfully.
? Select the repositories you want to delete:
 avalon-hw/third_party_lwip 🔗
✖ Failed to delete repository avalon-hw/third_party_lwip 🔗. Request failed with status code 404
Error details: Request failed with status code 404
All selected repositories have been deleted.

**Comment by yaolifeng0629** [comment]
@FergusHuang Thank your feedback, This issue has been fixed. You can install the latest version [@1.1.1](https://www.npmjs.com/package/del-repos)
