### ISSUE TITLE
[feat] 只列出当前用户的，过滤掉组织的项目

### ISSUE THREAD

**Issue by ayangweb** [yaolifeng0629/del-repos#15]
大佬是不是可以加一个功能如题所示的功能？

**Comment by ayangweb** [comment]
<img width="1043" alt="image" src="https://github.com/user-attachments/assets/c433b0e0-7903-430a-9446-4651fece00cf">

怪了，安装不上！

**Comment by yaolifeng0629** [comment]
我刚安装成功了

1. 可能刚才 npm 包有缓存，还未更新上去，你可以重新安装试一下
2. 你可以检查下你的镜像源是否正确

![Clip_2024-11-06_23-49-42](https://github.com/user-attachments/assets/da629442-08dd-4213-9373-4a1801a147d5)

**Comment by ayangweb** [comment]
缓存我删过了，还是不行，我本地跑起来了！

**Comment by yaolifeng0629** [comment]
可以的，使用愉快~

**Comment by ayangweb** [comment]
镜像问题，忘了用的淘宝镜像了😂

**Comment by ayangweb** [comment]
大佬，辛苦了🌹

**Comment by yaolifeng0629** [comment]
客气了，兄弟

记得切换 npmmirror 镜像

**Comment by ayangweb** [comment]
嗯嗯，不知道啥时候换的淘宝，我一直一位是 npm 的🤣

**Comment by yaolifeng0629** [comment]
哈哈，有点时间了，问题不大
